apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-configmap
  namespace: ecommerce
data:
  POSTGRES_URI :  'postgresql://postgres:ecommerce@database-postgres-service:5432/ecommerce'
  POSTGRES_URI_STOCK : 'postgresql://postgres:ecommerce@database-postgres-service:5432/ecommerce?schema=products'
  MONGO_URI_USER:  'mongodb://web-0.database-mongo-service:27017/ecommerce?directConnection=true'
  MONGO_URI_ORDER:  'mongodb://web-1.database-mongo-service:27017/ecommerce?directConnection=true'
