apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-iam-live-deployment
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-iam-live
  template:
    metadata:
      labels:
        app: "ms-iam-live"
    spec:
      containers:
      - name: ms-iam-live-container
        image: localhost:5001/ms-iamlive:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ms-iam-live-service
  namespace: ecommerce
spec:
  selector:
    app: ms-iam-live
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
