apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-users-deployment
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "ms-users"
  template:
    metadata:
      labels:
        app: "ms-users"
    spec:
      containers:
      - name: ms-users-container
        image: localhost:5001/ms-users:latest
        env:
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: ecommerce-configmap
                key: MONGO_URI_USER
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: "ms-users-service"
  namespace: ecommerce
spec:
  selector:
    app: "ms-users"
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
