apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: ecommerce
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= #echo -n "postgres" | base64
  POSTGRES_PASSWORD: ZWNvbW1lcmNl #echo -n "ecommerce" | base64
  POSTGRES_DB: ZWNvbW1lcmNl #echo -n "ecommerce"  | base64 

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app:   "database-postgres"
  template:
    metadata:
      labels:
        app: "database-postgres"
    spec:
      containers:
      - name: postgres-container
        image: localhost:5001/postgres:16.0-alpine3.18
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ecommerce-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: ecommerce-secret
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: ecommerce-secret
                key: POSTGRES_USER
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"

---


apiVersion: v1
kind: Service
metadata:
  name: database-postgres-service
  namespace: ecommerce
spec:
  selector:
    app: database-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

# ---


# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: deny-external-database-postgres
# spec:
#   podSelector:
#     matchLabels:
#       app: database-postgres
#   ingress:
#   - from:
#     - namespaceSelector:
#         matchLabels:
#           purpose: internal
#   egress:
#   - to:
#     - ipBlock:
#         cidr: 0.0.0.0/0
